### ISSUE TITLE
ScrolledView Issue

### ISSUE THREAD

**Issue by hoseck** [linux4sam/egt#16]
If I change the ScrollWheel on the ScrolledView, the contents look overlapping as shown in the figure.
![image](https://user-images.githubusercontent.com/31186284/114805458-08bf7e00-9dde-11eb-9dcc-1e0cd871e7a9.png)

**Comment by ldesroches** [comment]
Hi,

Thanks for the report. We'll have a look.

Regards,
Ludovic

**Comment by ldesroches** [comment]
Hi @hoseck 

Fix pushed. Let me know if's ok and if it doesn't have nasty side effects for your app.

Regards,
Ludovic

**Comment by hoseck** [comment]
This bug still hasn't been fixed.
ScrollWheel Widget works well on the Notebook Tab. As you can see on the screen, there is a problem that text overlaps in ScrollView.
Please check again.

**Comment by ldesroches** [comment]
Hi @hoseck 

I get a notification where you said it was not solved but there is no comment here. Did you delete it? Is it solved?

If it's not solved with the master branch, is there a way you share your code. I was able to reproduce the issue and it's fixed on my side but maybe some cases are not handled correctly.

Regards,
Ludovic
